services:
  frontend:
    container_name: pos-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8034:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - kafe-network

networks:
  kafe-network:
    driver: bridge
